[tools]
awscli = "2.20.0"
gcloud = "501.0.0"
github-cli = "2.61.0"
jq = "1.7.1"
kubectl = "1.31.2"
neovim = "0.11.6"
shellcheck = "0.10.0"
snyk = "1.1301.1"
steampipe = "2.4.0"
teleport-ent = "18.2.0"
