[aws]
#force_display = true
#format = 'on [$symbol($profile )(\($region\) )]($style)'
#symbol = '🅰 '
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = ""
style = "bold white"
format = '[\($symbol$branch\)]($style) '

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count} "
behind = "🐢 ×${count} "
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count} "
untracked = "🛤️  ×${count} "
stashed = "📦 "
modified = "📝 ×${count} "
staged = "🗃️  ×${count} "
renamed = "📛 ×${count} "
deleted = "🗑️  ×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"
